import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "@/components/Navbar/ResponsiveNav";
import Footer from "@/components/Footer/Footer";

import ReduxProvider from "@/components/ReduxProvider";
import ScrollToTop from "@/components/helper/ScrollToTop";
import PageLoader from "@/components/helper/PageLoader";

const font = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "Learning Needs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className}`}
      >
        <ReduxProvider>
          <PageLoader />
          <ResponsiveNav />
          {children}
          <Footer />
          <ScrollToTop />
        </ReduxProvider>

      </body>
    </html>
  );
}
