export const coursesData = [
  {
    id: 1,
    image: "/course/1.jpg",
    title: "Medical Assistant",
    price: 3000,
    teacher: "John Doe",
    reviewNumber: 450,
    weeks: 15,
    hours: 300,
    category: "Medical",
    preRequisite: "GED/High school diploma",
    certification: " Certified Medical Assistant (CMA)",
    description: `The Medical Assistant program is an entry-level program that teaches students various technical clinical skills. A student will be taught the role of the Medical Assistant in the medical office, front office procedures, clinical areas including phlebotomy, EKGs, HIPAA compliance, and more.`,
  },
  {
    id: 2,
    image: "/course/2.avif",
    title: "Med. Billing & Coding",
    price: 4000,
    teacher: "John Doe",
    reviewNumber: 450,
    weeks: 15,
    hours: 300,
    category: "Medical",
    preRequisite: "GED/High school diploma",
    certification: " National Health Care Association",
    description: `This program is a 300-hour entry level program that teaches a student how to work in the insurance and health claims examination side of healthcare. This program begins by introducing medical terminology including analogy and physiology, prefixes, suffixes and word roots, definition and medical offices procedures such as medical office, protocol, and use of office equipment and components of a patient chart, confidentiality and HIPAA, completion of patient forms, filing and telephone etiquette. The student then advances into the medical billing and coding module, which teaches a student how to do ICD-10 coding, CPT coding, completing claim forms with insurance companies, ethics and law, common billing terminology, how to review claims forms, how to maintain a billing system and how to maintain patient records.`,
  },
  {
    id: 3,
    image: "/course/3.avif",
    title: "Electrocardiogram",
    price: 4000,
    teacher: "John Doe",
    reviewNumber: 450,
    weeks: 4,
    hours: 80,
    category: "Medical",
    preRequisite: "GED/High school diploma",
    certification: " Certificate of Completion",
    description: `This course will provide you with an overview of basic cardiovascular terminology, anatomy and physiology. Focuses on the proper placement of electrocardiogram (EKG) leads and maintenance of equipment to obtain an accurate 12-Lead EKG. Learn to recognize cardiac arrhythmias. Outlines responsibilities of ECG\EKG technicians and provides clinical laboratory opportunity to develop entry level skills. Upon successful completion of this course, students will receive a certificate of completion and will be eligible for National Certification through the American Medical Certification Association AMCA.`,
  },
  {
    id: 4,
    image: "/course/4.avif",
    title: "Phlebotomy",
    price: 4000,
    teacher: "John Doe",
    reviewNumber: 450,
    weeks: 4,
    hours: 80,
    category: "Medical",
    preRequisite: "GED/High school diploma",
    certification: " National Health Association",
    description: `This course prepares an individual for employment in the medical industry. Students will get training in different aspects of Phlebotomy. The phlebotomist’s job description focuses on the responsibility of taking blood from patients and properly labelling samples with the patient information and lab test orders from the doctor. Blood drawn by phlebotomists can also help doctors track a patient’s wellbeing and determine if a particular treatment is working.`,
  },
  {
    id: 5,
    image: "/course/5.avif",
    title: "Hospitality Management",
    price: 4000,
    teacher: "John Doe",
    reviewNumber: 450,
    weeks: 22,
    hours: 440,
    category: "Hospitality",
    preRequisite: "GED/High school diploma",
    certification: "AHLEI (American Hotel and Lodging Education Institute)",
    description: `The goal of the program is to prepare hospitality management students with entry-level management positions in the foodservice, lodging, and gaming industries with the management and customer relations skills necessary for this profession. This program will also prepare the students for entry-level food service management positions. It will provide a foundation in foodservice management while focusing on basic food preparation, management, and business practices. The program offers students a strong business and customer service foundation required for careers in this dynamic and expanding service.`,
  },
  {
    id: 6,
    image: "/course/6.avif",
    title: "Web Design",
    price: 2500,
    teacher: "John Doe",
    reviewNumber: 450,
    weeks: 15,
    hours: 300,
    category: "Technology",
    preRequisite: "GED/High school diploma",
    certification: "Certificate of Completion",
    description: `Students will develop awareness and appreciation of the myriad ways that people access the web and will be able to create standards-based websites that are accessible and usable by a full spectrum of users. This program delivers a well-rounded education in all aspects of website creation – front-end design, back-end development, and client-side scripting development and deployment.`,
  },
  {
    id: 7,
    image: "/course/7.avif",
    title: "Office Management - Computer Basics",
    price: 2500,
    teacher: "John Doe",
    reviewNumber: 450,
    weeks: 10,
    hours: 200,
    category: "Technology",
    preRequisite: "GED/High school diploma",
    certification: "Certificate From Microsoft",
    description: `This 200-hour program provides students with detail introduction to computer basics, understanding of Computer Hardware and Software, detail understanding of different Operating Systems, different tools of Microsoft Office, Internet tools and Network.`,
  },
  {
    id: 8,
    image: "/course/8.avif",
    title: "Computer Support Specialist",
    price: 2500,
    teacher: "John Doe",
    reviewNumber: 450,
    weeks: 18,
    hours: 350,
    category: "Technology",
    preRequisite: "GED/High school diploma",
    certification: "Certificate of Completion",
    description: `Through hands-on coursework, a student will learn to help end users on the enterprise to administer, troubleshoot and deploy its servers. In this program students will actively learn the fundamentals of computer and networking technologies to meet the demands of the dynamic industry. The courses will comprise of: Basics in Information Systems, Managing the Windows Desktop, Network +, CompTIA A+, HDI Support Center Analyst (HDI-SCA), The Project Management Framework and its relationship with Information Systems, and the Microsoft Office User Applications, Information Systems, Operating Systems and Networking.`,
  },
  {
    id: 9,
    image: "/course/9.avif",
    title: "Solar Panel Installer",
    price: 4000,
    teacher: "John Doe",
    reviewNumber: 450,
    weeks: 12,
    hours: 240,
    category: "Skilled Labor",
    preRequisite: "GED/High school diploma",
    certification: "NABCEP Certified Solar Panel Installer",
    description: `The course gives an understanding of the core concepts necessary to work with both residential and commercial PV systems. Topics include system components, sit analysis, PV module criteria, mounting solutions, safety, and commissioning. Participants will learn the fundamentals of sizing a residential battery-less grid-tied system, wire sizing, over-current protection, and grounding. This session will also review fundamental design criteria for off-grid stand-alone systems including specifying batteries, controllers, and battery-based inverters.`,
  },
  {
    id: 10,
    image: "/course/10.avif",
    title: "Java Programmer",
    price: 2500,
    teacher: "John Doe",
    reviewNumber: 450,
    weeks: 10,
    hours: 200,
    category: "Skilled Labor",
    preRequisite: "GED/High school diploma",
    certification: "Life Time Job Support",
    description: `Students will develop awareness and detail understanding of Java Enterprise Edition. Students will be able to create standards-based websites that are accessible and usable by a full spectrum of users. This program delivers a well-rounded education in all aspects of Java Programming – front-end and back-end.`,
  },
  {
    id: 11,
    image: "/course/11.avif",
    title: "Business Analyst",
    price: 2500,
    teacher: "John Doe",
    reviewNumber: 450,
    weeks: 10,
    hours: 200,
    category: "Business",
    preRequisite: "GED/High school diploma",
    certification: "Life Time Job Support",
    description: `This course prepares an individual for employment in a Business Analyst industry. Students will be trained in different aspects of the Business Analyst field which will range from Enterprise Analysis to Project Planning and Management. This will increase students’ business awareness and accountability while also gaining marketable skills. A Business analyst provides and analyses an organization or business domain and documents its business or processes.`,
  },
  {
    id: 12,
    image: "/course/12.avif",
    title: "Landscaping & Groundskeeping",
    price: 4000,
    teacher: "John Doe",
    reviewNumber: 450,
    weeks: 15,
    hours: 300,
    category: "Skilled Labor",
    preRequisite: "GED/High school diploma",
    certification: "National Association of Landscaping Professionals",
    description: `The course gives overview of potential career paths and professional development available for students who formally develop skills and knowledge related to building construction. This program includes a summary of math and science concepts important to building professionals as well as applications of modern technologies to the construction workplace. The program concludes with an overview of general workplace safety practices and applications of personal protection equipment.`,
  },
  {
    id: 13,
    image: "/course/13.avif",
    title: "Cisco Certified Network Associate",
    price: 2500,
    teacher: "John Doe",
    reviewNumber: 450,
    weeks: 12,
    hours: 240,
    category: "Technology",
    preRequisite: "GED/High school diploma",
    certification: "CISCO Certification",
    description: `This program teaches networking concepts using a top-down, theoretical and integrated approach from network applications by the lower layers of the network. The program emphasizes areas of the network consisting of Internet Working (Basics), managing a Cisco Internetwork, IP Routing, Virtual LANs, wide-area Networks, and other major networking topics in the industry.`,
  },
  {
    id: 14,
    image: "/course/14.avif",
    title: "Patient Care Technician",
    price: 4000,
    teacher: "John Doe",
    reviewNumber: 450,
    weeks: 15,
    hours: 300,
    category: "Medical",
    preRequisite: "GED/High school diploma",
    certification: "National Health Care Association",
    description: `The Patient Care technician program is an entry level program that incorporated three important health cares into one program. The program teaches a student medical terminology, analogy, physiology, prefixes, suffixes word roots, defamations, entry level anatomy and physiology, medical office protocol, ethics and laws, HIPAA and confidentiality regulations, completing and maintaining patient medical records, filling, telephone etiquette, typing, completion of patient forms basic computer skills, medical billing and medical coding. A graduate of the program will be able to apply in various healthcare settings such as Physician offices, clinics, laboratories and / or hospitals. This is an ideal program for someone who wants to work in healthcare but may not want to perform clinical procedures.`,
  },
  {
    id: 15,
    image: "/course/res.jpg",
    title: "Resident Electrician",
    price: 4000,
    teacher: "John Doe",
    reviewNumber: 450,
    weeks: 8,
    hours: 240,
    category: "Skilled Labor",
    preRequisite: "GED/High school diploma",
    certification: "OSHA 30",
    description: `The Resident Electrician Program is an Entry Level Program which introduces you to the basics of Electrical Fundamentals, Electrical Safety and Tools Used and progresses to the advanced concepts of Cables and Conductors, National Electrical Codes, HVAC Systems, Reading Electrical Drawings, and Blueprints.The Program will train you to work in Residential and Commercial Electrical work.`,
  },
  {
    id: 16,
    image: "/course/16.avif",
    title: "Home Health Aide",
    price: 4000,
    teacher: "John Doe",
    reviewNumber: 450,
    weeks: 8,
    hours: 240,
    category: "Medical",
    preRequisite: "GED/High school diploma",
    certification: "Life Time Job Support",
    description: `The Resident Electrician Program is an Entry Level Program which introduces you to the basics of Electrical Fundamentals, Electrical Safety and Tools Used and progresses to the advanced concepts of Cables and Conductors, National Electrical Codes, HVAC Systems, Reading Electrical Drawings, and Blueprints.The Program will train you to work in Residential and Commercial Electrical work.`,
  },

  {
    id: 17,
    image: "/course/comp.jpg",
    title: "CompTIA A+",
    price: 2500,
    teacher: "John Doe",
    reviewNumber: 450,
    weeks: 2,
    hours: 40,
    category: "Technology",
    preRequisite: "GED/High school diploma",
    certification: "CompTIA Certification (220-1001)",
    description: `Beginners looking to start a career in information technology Aspiring IT support specialists and help desk technicians Professionals preparing for the CompTIA A+ certification exams Anyone looking to build fundamental knowledge in computer hardware and networking`,
  },
];

export const quickProgramsData = [
  {
    id: 1,
    image: "/images/c1.jpg",
    title: "Java Programmer",
    description:
      " Become a certified Java Programmer with our comprehensive program.",
    price: 2500,
    duration: "4 weeks",
    hours: "will be informed",
    category: "Programming",
    reviewNumber: 430,
  },
  {
    id: 2,
    image: "/images/c1.jpg",
    title: "COMPTIA A+",
    description:
      "Build a strong foundation in IT support, troubleshooting, hardware, and networking to prepare for the globally recognized CompTIA A+ certification.",
    price: 2500,
    duration: "4 weeks",
    hours: "will be informed",
    category: "Programming",
    reviewNumber: 430,
  },
  {
    id: 3,
    image: "/images/c1.jpg",
    title: "Cisco Certified Network Associate",
    description:
      "Learn essential networking concepts, routing, switching, and security fundamentals to master core Cisco technologies and advance your IT career.",
    price: 2500,
    duration: "4 weeks",
    hours: "will be informed",
    category: "Programming",
    reviewNumber: 430,
  },
];

export const articleData = [
  {
    id: 1,
    userImage: "/images/u1.jpg",
    username: "John Doe",
    longDescription: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. `,
    reaction: 45,
    coverImage: "/images/b1.jpg",
    title: "Understanding JavaScript",
  },
  {
    id: 2,
    userImage: "/images/u2.jpg",
    username: "Jane Smith",
    longDescription: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. `,
    reaction: 78,
    coverImage: "/images/b2.jpg",
    title: "A Guide to Node.js Event Loop",
  },
  {
    id: 3,
    userImage: "/images/u3.jpg",
    username: "Alex Johnson",
    longDescription: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. `,
    reaction: 62,
    coverImage: "/images/b3.jpg",
    title: "Introduction to React Hooks",
  },
];
export const galleryData = [
  {
    id: 1,
    image:
      "https://img.freepik.com/free-photo/group-happy-students-standing-outdoors_23-2149153735.jpg",
  },
  {
    id: 2,
    image:
      "https://img.freepik.com/free-photo/smiling-students-walking-campus_23-2149160068.jpg",
  },
  {
    id: 3,
    image:
      "https://img.freepik.com/free-photo/portrait-student-outdoors_23-2149171906.jpg",
  },
  {
    id: 4,
    image:
      "https://img.freepik.com/free-photo/young-people-studying-together_23-2149159643.jpg",
  },
  {
    id: 5,
    image:
      "https://img.freepik.com/free-photo/people-working-laptop-classroom_23-2149042477.jpg",
  },
  {
    id: 6,
    image:
      "https://img.freepik.com/free-photo/smiling-group-students-holding-books_23-2149202292.jpg",
  },
  {
    id: 7,
    image:
      "https://img.freepik.com/free-photo/teacher-helping-student-class_23-2149039511.jpg",
  },
  {
    id: 8,
    image:
      "https://img.freepik.com/free-photo/student-writing-notebook-classroom_23-2149039508.jpg",
  },
  {
    id: 9,
    image:
      "https://img.freepik.com/free-photo/happy-students-studying-together_23-2149210689.jpg",
  },
  {
    id: 10,
    image:
      "https://img.freepik.com/free-photo/students-sitting-desk-learning_23-2148898746.jpg",
  },
  {
    id: 11,
    image:
      "https://img.freepik.com/free-photo/group-students-studying-library_23-2148898752.jpg",
  },
  {
    id: 12,
    image:
      "https://img.freepik.com/free-photo/group-young-people-studying-together-table_23-2149178073.jpg",
  },
];
